declare const styles: {
  readonly 'category-header': string;
  readonly 'category-icon': string;
  readonly 'category-title': string;
  readonly 'project-card': string;
  readonly 'project-date': string;
  readonly 'project-header': string;
  readonly 'project-image': string;
  readonly 'project-info': string;
  readonly 'project-tags': string;
  readonly 'project-title': string;
  readonly 'skill-category': string;
  readonly 'skill-icon-img': string;
  readonly 'skill-icon-wrapper': string;
  readonly 'skill-icons-grid': string;
  readonly 'skills-container': string;
  readonly tag: string;
  readonly 'tag-blue': string;
  readonly 'tag-emerald': string;
};
export = styles;
