declare const styles: {
  readonly backdrop: string;
  readonly modal: string;
  readonly 'close-button': string;
  readonly 'image-container': string;
  readonly image: string;
  readonly content: string;
  readonly header: string;
  readonly title: string;
  readonly category: string;
  readonly 'info-grid': string;
  readonly 'info-item': string;
  readonly tags: string;
  readonly tag: string;
  readonly section: string;
  readonly 'section-title': string;
  readonly description: string;
  readonly list: string;
  readonly 'list-item': string;
  readonly 'tech-stack': string;
  readonly 'tech-category': string;
  readonly 'tech-title': string;
  readonly 'tech-tags': string;
  readonly 'tech-tag': string;
  readonly actions: string;
  readonly 'action-button': string;
};
export default styles;
