declare const styles: {
  readonly 'contact-info-section': string;
  readonly 'contact-list': string;
  readonly 'contact-section': string;
  readonly container: string;
  readonly 'content-grid': string;
  readonly description: string;
  readonly footer: string;
  readonly form: string;
  readonly 'form-group': string;
  readonly 'form-section': string;
  readonly header: string;
  readonly input: string;
  readonly label: string;
  readonly 'section-title': string;
  readonly 'social-links': string;
  readonly 'social-title': string;
  readonly 'submit-button': string;
  readonly textarea: string;
  readonly title: string;
};
export = styles;
